### PR TITLE
Update clear_cart_steps.java

### PR DESCRIPTION
**Pull request by pierluigi**

### CODE REVIEW

**Comment by pierluigi** [comment]
@edgewords I've followed the steps to include the right `refspec` as [defined here](https://github.com/jenkinsci/ghprb-plugin/blob/master/README.md#creating-a-job). Let's see if this works...

**Comment by pierluigi** [comment]
I think that did it!
```

  Scenario: Add a Cap                              # Add Items to Cart_5054.feature:5
    Given That I am on the Home Page               # add_items_to_cart_steps.that_I_am_on_the_Home_Page()
    When I search for a Cap and add it to the Cart # add_items_to_cart_steps.i_search_for_a_Cap_and_add_it_to_the_Cart()
    Then I can see it in the Cart                  # add_items_to_cart_steps.i_can_see_it_in_the_Cart()
#Auto generated Octane revision tag
@TID6069REV0.2.0
Feature: Shopping Cart

  Scenario: Clear Cart                        # Clear Cart-6069.feature:5
    Given There are items inthe shopping cart # clear_cart_steps.there_are_items_inthe_shopping_cart()
      cucumber.api.PendingException: TODO: implement me
      	at code_bindings.clear_cart_steps.there_are_items_inthe_shopping_cart(clear_cart_steps.java:15)
      	at ?.Given There are items inthe shopping cart(Clear Cart-6069.feature:6)
      
    When I clear the cart                     # clear_cart_steps.i_clear_the_cart()
    Then the cart should be empty             # clear_cart_steps.the_cart_should_be_empty()

2 Scenarios (1 pending, 1 passed)
6 Steps (2 skipped, 1 pending, 3 passed)
0m18.500s
```

**Comment by pierluigi** [comment]
Although it seems like this should have reported as a failure.

**Comment by edgewords** [comment]
I’ll try it now…

**Comment by pierluigi** [comment]
```
[WARNING] Tests run: 9, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 19.12 s - in runners.MyRunner
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 8, Failures: 0, Errors: 0, Skipped: 3
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Pull request closed without merging**
